name: Postman Collection Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: 30 02 * * *
    - cron: 00 14 * * *
    - cron: 00 06 * * 1-5

jobs:
  run-Postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v5.0.0

      - name: Install Node.js and npm
        uses: actions/setup-node@v6.0.0
        with:
          node-version: '22'

      - name: Install Newman and HTML Extra Reporter
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Postman collection with Newman
        run: |
          newman run 'IWarrantyWorkflowCollection-updated.postman_collection.json' \
          -e GlobalVaiable_QAEnv.postman_environment.json \
          -r cli,htmlextra

          name : Newman Report
          if:always()
              uses: actions/upload-artifact@v4.6.2
              name : Newman Report
              path : newman/.html

            name : creatig Github page branch
             if : always()
             user: peaceiris/actions-github-pages@v3.1.12
             with :
               github_token :${{ secrrets.GITHUB_TOKEN }}
               publish_dir: newman/
             

          
          
