name: Postman Collection Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '30 02 * * *'
    - cron: '00 14 * * *'
    - cron: '00 06 * * 1-5'

jobs:
  run-Postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v5

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman and HTML Extra Reporter
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Postman collection with Newman
        run: |
          newman run 'IWarrantyWorkflowCollection-updated.postman_collection.json' \
          -e GlobalVaiable_QAEnv.postman_environment.json \
          -r cli,htmlextra

      - name: Upload Newman Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Newman Report
          path: newman/

      - name: Create GitHub Pages branch
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/

      - name: Send Email Notification
        if: always()
        uses: hemupadhyay26/action-email-notification@v1.1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          subject: phoenix-InWarranty-Flow Email Notification
          recipients: poonam.joshiit@gmail.com
          body: |
            Hi Team,
            Please find status of Testing Automation.
